[package]
name = "lossrs_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lossrs_util = { path = "../util" }

[lib]
proc-macro = true
